In [4]:
import torch

#### continuous


In [6]:
base = torch.tensor([[0, 1],[2, 3]])
base.is_contiguous()

True

In [7]:
t = base.transpose(0, 1)
t.is_contiguous()

False

In [9]:
v = t.view([2,2])

In [11]:
v.is_contiguous()

False

In [14]:
c = t.contiguous()
c.is_contiguous()

True

In [16]:
print(base)

tensor([[0, 1],
        [2, 3]])


In [17]:
print(v)
print(c)

tensor([[0, 2],
        [1, 3]])
tensor([[0, 2],
        [1, 3]])
