In [1]:
import torch

# tensor indices

### mask tensor indices
조건
- tensors used as indices must be long, byte or bool tensors

In [4]:
s = torch.randn((5,5))
s

tensor([[ 0.1244, -1.0632, -0.1589, -2.8850,  0.1213],
        [ 0.5642,  0.6917, -0.1726, -0.9508,  0.8776],
        [-2.8092, -1.3188, -1.6327, -1.2065, -1.6319],
        [ 0.8121, -0.1349,  1.7144,  0.3778, -0.7598],
        [ 0.0965,  0.4136, -0.1915,  0.4389,  0.4341]])

In [5]:
data = s <= 0

In [6]:
data

tensor([[False,  True,  True,  True, False],
        [False, False,  True,  True, False],
        [ True,  True,  True,  True,  True],
        [False,  True, False, False,  True],
        [False, False,  True, False, False]])

In [8]:
mapped = s[data]
mapped

tensor([-1.0632, -0.1589, -2.8850, -0.1726, -0.9508, -2.8092, -1.3188, -1.6327,
        -1.2065, -1.6319, -0.1349, -0.7598, -0.1915])

In [9]:
mapped.shape

torch.Size([13])

# error

### IndexError: too many indices for tensor of dimension 4
이러한 에러를 종종 보게 되는데, 보통 아래의 경우다.
- 사용하는 종속성이 Tensor 를 받지 않고, dict of tensors 를 받았던 경우
    - `{'low_level': torch.zeros([2,3,256,256]), 'out':: torch.zeros([2,2048,56,56])}` 을 입력시켜줘야 한다.

In [17]:
def test(dict_of_tensors):
    return torch.nn.functional.interpolate(dict_of_tensors['out'], scale_factor=0.5)

In [18]:
test(torch.zeros([2,3,256,256]))

TypeError: new(): invalid data type 'str'

In [20]:
dict_of_tensors = {'out': torch.zeros([2,3,256,256])}
test(dict_of_tensors).shape

torch.Size([2, 3, 128, 128])