# split
`torch.split(tensor, split_size_or_sections, dim=0)`


### split_size 로 나누기

In [1]:
import torch

In [3]:
a = torch.rand((1,2,3,4))

In [5]:
b = torch.split(a, 2, dim=3)
b

(tensor([[[[0.1970, 0.0876],
           [0.7976, 0.8792],
           [0.3144, 0.4294]],
 
          [[0.7317, 0.4964],
           [0.9385, 0.3812],
           [0.9331, 0.9704]]]]),
 tensor([[[[0.1450, 0.3535],
           [0.6509, 0.4527],
           [0.7123, 0.4063]],
 
          [[0.7226, 0.5470],
           [0.4312, 0.8324],
           [0.0510, 0.9816]]]]))

In [6]:
print(len(b), b[0].shape, b[1].shape)

2 torch.Size([1, 2, 3, 2]) torch.Size([1, 2, 3, 2])


### sections 로 나누기

In [8]:
b = torch.split(a, [1,3], dim=3)
b

(tensor([[[[0.1970],
           [0.7976],
           [0.3144]],
 
          [[0.7317],
           [0.9385],
           [0.9331]]]]),
 tensor([[[[0.0876, 0.1450, 0.3535],
           [0.8792, 0.6509, 0.4527],
           [0.4294, 0.7123, 0.4063]],
 
          [[0.4964, 0.7226, 0.5470],
           [0.3812, 0.4312, 0.8324],
           [0.9704, 0.0510, 0.9816]]]]))

In [9]:
print(len(b), b[0].shape, b[1].shape)

2 torch.Size([1, 2, 3, 1]) torch.Size([1, 2, 3, 3])
