In [2]:
import torch
import numpy as np

In [7]:
import torch.nn.functional as F

# activation functions

## log_softmax

In [3]:
A = np.eye(2) * 2
B = np.eye(3) * 3
block = np.block([
    [A,               np.zeros((2, 3))],
    [np.ones((3, 2)), B               ]
])

In [4]:
block

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

In [5]:
block.shape

(5, 5)

In [6]:
block_tensor = torch.tensor(block)

In [8]:
F.log_softmax(block_tensor)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([[-0.4327, -2.4327, -2.4327, -2.4327, -2.4327],
        [-2.4327, -0.4327, -2.4327, -2.4327, -2.4327],
        [-2.3150, -2.3150, -0.3150, -3.3150, -3.3150],
        [-2.3150, -2.3150, -3.3150, -0.3150, -3.3150],
        [-2.3150, -2.3150, -3.3150, -3.3150, -0.3150]], dtype=torch.float64)

In [9]:
F.log_softmax(block_tensor, dim=0)

tensor([[-0.8060, -2.8060, -3.1816, -3.1816, -3.1816],
        [-2.8060, -0.8060, -3.1816, -3.1816, -3.1816],
        [-1.8060, -1.8060, -0.1816, -3.1816, -3.1816],
        [-1.8060, -1.8060, -3.1816, -0.1816, -3.1816],
        [-1.8060, -1.8060, -3.1816, -3.1816, -0.1816]], dtype=torch.float64)

In [10]:
F.log_softmax(block_tensor, dim=1)

tensor([[-0.4327, -2.4327, -2.4327, -2.4327, -2.4327],
        [-2.4327, -0.4327, -2.4327, -2.4327, -2.4327],
        [-2.3150, -2.3150, -0.3150, -3.3150, -3.3150],
        [-2.3150, -2.3150, -3.3150, -0.3150, -3.3150],
        [-2.3150, -2.3150, -3.3150, -3.3150, -0.3150]], dtype=torch.float64)

In [18]:
a = np.ones((1,2,2))
b = np.zeros((1,2,2))
block = np.concatenate((a, b), axis=0)

In [20]:
block

array([[[1., 1.],
        [1., 1.]],

       [[0., 0.],
        [0., 0.]]])

In [19]:
block.shape

(2, 2, 2)

In [21]:
block_tensor = torch.tensor(block)

In [23]:
F.log_softmax(block_tensor, dim=0)

tensor([[[-0.3133, -0.3133],
         [-0.3133, -0.3133]],

        [[-1.3133, -1.3133],
         [-1.3133, -1.3133]]], dtype=torch.float64)

In [22]:
F.log_softmax(block_tensor, dim=1)

tensor([[[-0.6931, -0.6931],
         [-0.6931, -0.6931]],

        [[-0.6931, -0.6931],
         [-0.6931, -0.6931]]], dtype=torch.float64)

In [24]:
t = torch.tensor([[[0.,0.,1.],[100.,0.,0.]],
                  [[0.,1.,0.],[-1.,0.,0.]]])
print(t.shape)
F.log_softmax(t, dim=2)

torch.Size([2, 2, 3])


tensor([[[  -1.5514,   -1.5514,   -0.5514],
         [   0.0000, -100.0000, -100.0000]],

        [[  -1.5514,   -0.5514,   -1.5514],
         [  -1.8620,   -0.8620,   -0.8620]]])

In [25]:
t = torch.tensor([[[0.,0.,1.],[100.,0.,0.]],
                  [[0.,1.,0.],[-1.,0.,0.]]])
print(t.shape)
F.log_softmax(t, dim=1)

torch.Size([2, 2, 3])


tensor([[[-100.0000,   -0.6931,   -0.3133],
         [   0.0000,   -0.6931,   -1.3133]],

        [[  -0.3133,   -0.3133,   -0.6931],
         [  -1.3133,   -1.3133,   -0.6931]]])

In [26]:
t = torch.tensor([[[0.,0.,1.],[100.,0.,0.]],
                  [[0.,1.,0.],[-1.,0.,0.]]])
print(t.shape)
F.log_softmax(t, dim=0)

torch.Size([2, 2, 3])


tensor([[[  -0.6931,   -1.3133,   -0.3133],
         [   0.0000,   -0.6931,   -0.6931]],

        [[  -0.6931,   -0.3133,   -1.3133],
         [-101.0000,   -0.6931,   -0.6931]]])