# Deep Learning with PyTorch: A 60 Minute Blitz

## 1-1 What is pytorch

In [1]:
import IPython

In [2]:
IPython.lib.passwd()

Enter password: ········
Verify password: ········


'sha1:9a0221300c21:c887abd1fae7076c9e2cc16e1abc2d9ef88de4c8'

In [1]:
from __future__ import print_function
import torch


In [2]:
x = torch.empty(3,5)
print(x)

tensor([[-2.3405e-29,  4.5715e-41, -2.3405e-29,  4.5715e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [4]:
torch.rand(3,5)

tensor([[0.7211, 0.9144, 0.7571, 0.3450, 0.3198],
        [0.7452, 0.8340, 0.0701, 0.6232, 0.5273],
        [0.7815, 0.0502, 0.1844, 0.7008, 0.0356]])

In [5]:
torch.tensor([5.5, 3])

tensor([5.5000, 3.0000])

In [6]:
torch.tensor([0,0,1,0,0,0,1,0,0,1,0,0,0])

tensor([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [10]:
x = torch.zeros(3, 5)
print(x)
print(type(x))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
<class 'torch.Tensor'>


In [11]:
y = torch.rand(3, 5)
print(y)
z = y.new_ones(5, 3)
print(z)

tensor([[0.1397, 0.5625, 0.4319, 0.6259, 0.0220],
        [0.2774, 0.0939, 0.2063, 0.1046, 0.4656],
        [0.0666, 0.4895, 0.3572, 0.6547, 0.0672]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [12]:
y

tensor([[0.1397, 0.5625, 0.4319, 0.6259, 0.0220],
        [0.2774, 0.0939, 0.2063, 0.1046, 0.4656],
        [0.0666, 0.4895, 0.3572, 0.6547, 0.0672]])

In [13]:
torch.randn_like(y)

tensor([[ 1.1524, -0.3281,  2.2693, -0.8163,  1.5392],
        [ 0.3645, -0.8845, -1.1823,  1.1824, -0.1438],
        [ 0.1288,  1.4938,  0.0244,  1.3506,  0.5289]])

In [15]:
y.size()

torch.Size([3, 5])

In [17]:
a = y.new_ones(3,5)
print(y)
print(y + a)

tensor([[0.1397, 0.5625, 0.4319, 0.6259, 0.0220],
        [0.2774, 0.0939, 0.2063, 0.1046, 0.4656],
        [0.0666, 0.4895, 0.3572, 0.6547, 0.0672]])
tensor([[1.1397, 1.5625, 1.4319, 1.6259, 1.0220],
        [1.2774, 1.0939, 1.2063, 1.1046, 1.4656],
        [1.0666, 1.4895, 1.3572, 1.6547, 1.0672]])


### (t+t).pow(2)

In [19]:
t = torch.tensor([[1, 0], [0, 1]])

In [20]:
t

tensor([[1, 0],
        [0, 1]])

In [21]:
t + t

tensor([[2, 0],
        [0, 2]])

In [23]:
out = (t+t).pow(2)

In [24]:
out

tensor([[4, 0],
        [0, 4]])

In [25]:
out.sum()

tensor(8)

### backward 와 grad

In [32]:
a = torch.tensor([[2.,0.],[0.,2.]], requires_grad=True)

In [33]:
a

tensor([[2., 0.],
        [0., 2.]], requires_grad=True)

In [36]:
z = a.pow(2).sum()

In [37]:
z

tensor(8., grad_fn=<SumBackward0>)

In [38]:
z.backward()

In [39]:
a

tensor([[2., 0.],
        [0., 2.]], requires_grad=True)

In [40]:
a.grad

tensor([[4., 0.],
        [0., 4.]])

In [47]:
b = torch.tensor([[1.,0.],[0.,2.]], requires_grad=True)

In [48]:
b

tensor([[1., 0.],
        [0., 2.]], requires_grad=True)

In [49]:
zz = b.pow(2).sum()

In [50]:
zz

tensor(5., grad_fn=<SumBackward0>)

In [51]:
b.grad

In [52]:
zz.backward()

In [53]:
b.grad

tensor([[2., 0.],
        [0., 4.]])

### add 는 grad 가 True 면 쓸 수 없다

In [54]:
b

tensor([[1., 0.],
        [0., 2.]], requires_grad=True)

In [55]:
a

tensor([[2., 0.],
        [0., 2.]], requires_grad=True)

In [87]:
result = torch.empty(2,2)
torch.add(a,b, out=result)

RuntimeError: add(): functions with out=... arguments don't support automatic differentiation, but one of the arguments requires grad.

In [61]:
na = a.clone().detach()
print(na)

tensor([[2., 0.],
        [0., 2.]])


In [62]:
nb = b.clone().detach()
print(nb)

tensor([[1., 0.],
        [0., 2.]])


In [64]:
result = torch.empty(2,2)
torch.add(torch.tensor([[1., 1.],[2., 0.]]), torch.tensor([[1., 1.],[2., 0.]]), out=result)
print(result)

tensor([[2., 2.],
        [4., 0.]])


 ### [:,:1] vs. [:,0]

In [86]:
result

tensor([[2., 2.],
        [4., 0.]])

In [85]:
result[1:,:]

tensor([[4., 0.]])

In [75]:
result[:,1:]

tensor([[2.],
        [0.]])

In [76]:
result[:,1]

tensor([2., 0.])

In [77]:
print(result[:,:1])
print(result[:,0])

tensor([[2.],
        [4.]])
tensor([2., 4.])


### view vs. t

In [81]:
x = torch.rand(3,2)
print(x)
x.view(6)

tensor([[0.6626, 0.1288],
        [0.3813, 0.2466],
        [0.6794, 0.8347]])


tensor([0.6626, 0.1288, 0.3813, 0.2466, 0.6794, 0.8347])

In [83]:
x.view(2,3)

tensor([[0.6626, 0.1288, 0.3813],
        [0.2466, 0.6794, 0.8347]])

In [84]:
x.t()

tensor([[0.6626, 0.3813, 0.6794],
        [0.1288, 0.2466, 0.8347]])

### view(-1, 어쩌구) -1은 그 차원을 다른 것으로부터 추론하여 얻는다

In [88]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### add_

In [90]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [92]:
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [93]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [96]:
a.add_(torch.tensor([1.,2.,3.,4.,5.]))

tensor([3., 4., 5., 6., 7.])

In [97]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [98]:
torch.cuda.is_available()

False