In [1]:
import torch

In [12]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [13]:
x.repeat(1,1,1,3)

tensor([[[[1, 2, 3, 1, 2, 3, 1, 2, 3]]]])

In [7]:
y = x.repeat(4, 2)
y

tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])

In [8]:
y.shape

torch.Size([4, 6])

In [9]:
z = x.repeat(4, 2, 1)
z

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]])

In [10]:
z.shape

torch.Size([4, 2, 3])

In [14]:
x = torch.rand(1,3,5,5)
x

tensor([[[[0.2191, 0.4954, 0.6603, 0.2638, 0.3644],
          [0.3437, 0.7711, 0.9101, 0.6601, 0.2430],
          [0.0549, 0.8559, 0.0908, 0.4402, 0.4554],
          [0.5597, 0.3908, 0.6168, 0.6889, 0.9266],
          [0.8216, 0.0021, 0.7702, 0.1135, 0.1756]],

         [[0.6462, 0.8006, 0.3308, 0.4127, 0.9916],
          [0.7969, 0.0148, 0.1539, 0.9416, 0.1829],
          [0.5568, 0.4506, 0.1913, 0.8530, 0.0315],
          [0.7749, 0.0367, 0.0258, 0.5222, 0.2704],
          [0.8361, 0.0086, 0.7728, 0.4778, 0.4812]],

         [[0.7723, 0.3720, 0.9832, 0.4843, 0.5220],
          [0.8744, 0.1764, 0.2537, 0.8525, 0.6861],
          [0.4586, 0.8109, 0.8462, 0.2481, 0.2152],
          [0.8225, 0.8867, 0.0594, 0.7447, 0.9842],
          [0.1038, 0.4726, 0.2848, 0.8989, 0.8384]]]])

In [16]:
x.repeat(1,1,1,3).shape

torch.Size([1, 3, 5, 15])