In [2]:
import torch

#### tensor creation ops
https://pytorch.org/docs/1.1.0/torch.html#creation-ops

##### torch.tensor
  
constructs a tensor with data.


torch.tensor(  
    data,  
    dtype=None,  
    device=None,  
    requires_grad=False,  
    pin_memory=False)
  
* **data (array_like)** – Initial data for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types.
  
  
* dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, **infers data type from data**.
  
  
* device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.
* **requires_grad** (bool, optional) – If autograd should record operations on the returned tensor. **Default: False**.
* pin_memory (bool, optional) – If set, returned tensor would be allocated in the **pinned memory**. **Works only for CPU tensors**. Default: False.  
  

#### always copy 언제나 data 를 복사하여 만든다. 이를 피하려면 아래 방법을 쓰라.
`torch.tensor()` **always** copies data.  
If you have a **Tensor data** and want to avoid a copy, use `torch.Tensor.requires_grad_()` or `torch.Tensor.detach()`.  
If you have a **NumPy ndarray** and want to avoid a copy, use `torch.as_tensor()`.

#### tensor x : pass the data and constructs a leaf variable

When data is a **tensor x**, `torch.tensor()` reads out ‘the data’ from whatever it is passed,  
and constructs a leaf variable. 
  
  
Therefore `torch.tensor(x)` is equivalent to `x.clone().detach()` and  
`torch.tensor(x, requires_grad=True)` is equivalent to `x.clone().detach().requires_grad_(True)`.  
The equivalents using clone() and detach() are recommended.

In [3]:
help(torch.tensor)

Help on built-in function tensor:

tensor(...)
    tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False) -> Tensor
    
    Constructs a tensor with :attr:`data`.
    
    .. warning::
    
        :func:`torch.tensor` always copies :attr:`data`. If you have a Tensor
        ``data`` and want to avoid a copy, use :func:`torch.Tensor.requires_grad_`
        or :func:`torch.Tensor.detach`.
        If you have a NumPy ``ndarray`` and want to avoid a copy, use
        :func:`torch.as_tensor`.
    
    .. warning::
    
        When data is a tensor `x`, :func:`torch.tensor` reads out 'the data' from whatever it is passed,
        and constructs a leaf variable. Therefore ``torch.tensor(x)`` is equivalent to ``x.clone().detach()``
        and ``torch.tensor(x, requires_grad=True)`` is equivalent to ``x.clone().detach().requires_grad_(True)``.
        The equivalents using ``clone()`` and ``detach()`` are recommended.
    
    Args:
        data (array_like): Initial d

1. type inference on data

In [5]:
torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [6]:
torch.tensor([0, 1])

tensor([0, 1])

2. device

In [7]:
torch.tensor([[0.11111, 0.222222, 0.3333333]],
                 dtype=torch.float64,
                 device=torch.device('cpu:0'))  

tensor([[0.1111, 0.2222, 0.3333]], dtype=torch.float64)

3. zero dimensional tensor

In [8]:
torch.tensor(3.14159)  

tensor(3.1416)

4. empty tensor

In [9]:
torch.tensor([])

tensor([])