In [2]:
import torch

#### tensor indexing, slicing, joining, mutating ops
https://pytorch.org/docs/1.1.0/torch.html#indexing-slicing-joining-mutating-ops

##### torch.cat
  
concatenates the given sequence of seq tensors in the given dimension.  
**All tensors must either have the same shape or be empty.**

torch.cat(  
    tensors,  
    dim=0,  
    out=None)
  
* tensors (**sequence of Tensors**) – any python sequence of tensors of **the same type**. Non-empty tensors provided must have **the same shape**, except in the cat dimension.
  
  
* dim (int, optional) – the dimension over which the tensors are concatenated
* out (Tensor, optional) – the output tensor

In [3]:
help(torch.cat)

Help on built-in function cat:

cat(...)
    cat(tensors, dim=0, out=None) -> Tensor
    
    Concatenates the given sequence of :attr:`seq` tensors in the given dimension.
    All tensors must either have the same shape (except in the concatenating
    dimension) or be empty.
    
    :func:`torch.cat` can be seen as an inverse operation for :func:`torch.split`
    and :func:`torch.chunk`.
    
    :func:`torch.cat` can be best understood via examples.
    
    Args:
        tensors (sequence of Tensors): any python sequence of tensors of the same type.
            Non-empty tensors provided must have the same shape, except in the
            cat dimension.
        dim (int, optional): the dimension over which the tensors are concatenated
        out (Tensor, optional): the output tensor
    
    Example::
    
        >>> x = torch.randn(2, 3)
        >>> x
        tensor([[ 0.6580, -1.0969, -0.4614],
                [-0.1034, -0.5790,  0.1497]])
        >>> torch.cat((x, x, x), 0)
 

1. dim = 0

In [6]:
x = torch.randn(2,3)
x

tensor([[ 0.4159,  0.5323, -2.3233],
        [-0.6247,  0.4588,  0.5338]])

In [11]:
torch.cat((x,x,x),0).shape

torch.Size([6, 3])

2. dim = 1

In [8]:
x = torch.randn(2,3)
x

tensor([[ 0.0451,  0.9446, -0.2435],
        [-0.4654, -0.3893,  0.2272]])

In [10]:
torch.cat((x,x,x),1).shape

torch.Size([2, 9])