In [2]:
import torch

#### Convolution layers

##### convTranspose2d

torch.nn.convTranspose2d(  
    in_channels,  
    out_channels,  
    kernel_size,  
    stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros')

* in_channels (int): Number of channels in the input image
* out_channels (int): Number of channels produced by the convolution
* kernel_size (int or tuple): Size of the convolving kernel  
  
  
* stride (int or tuple, optional): Stride of the convolution. Default: 1
* padding (int or tuple, optional): ``dilation * (kernel_size - 1) - padding`` zero-padding will be added to both sides of the input. Default: 0
* output_padding (int or tuple, optional): Additional size added to one side of the output shape. Default: 0  
  
  
* groups (int, optional): Number of blocked connections from input channels to output channels. Default: 1
* bias (bool, optional): If ``True``, adds a learnable bias to the output. Default: ``True``
* dilation (int or tuple, optional): Spacing between kernel elements. Default: 1  


In [1]:
import torch.nn as nn

1. Kernel size = 3 은 (3,3)

In [3]:
m = nn.ConvTranspose2d(16, 33, 3, stride=2)

In [4]:
x = torch.randn(20, 16, 50, 100)
x

tensor([[[[ 2.6906e-02,  4.5937e-01, -6.5182e-01,  ...,  1.9950e+00,
            4.0205e-01,  1.8067e-01],
          [ 4.2790e-01,  4.5686e-01,  1.6588e-01,  ..., -1.0390e+00,
           -1.1673e+00, -7.7865e-01],
          [ 1.6122e+00, -2.1062e+00,  1.7099e+00,  ...,  9.5105e-01,
            3.2367e-01, -1.8081e-01],
          ...,
          [ 3.0357e+00, -1.3599e+00, -4.9280e-01,  ...,  3.6671e-01,
            6.4773e-01, -1.0770e+00],
          [-3.0754e-02,  9.9277e-01,  4.8344e-01,  ..., -3.6885e-01,
           -9.7977e-01,  5.9772e-01],
          [-8.0660e-02, -5.6638e-01, -5.6038e-02,  ...,  9.3263e-01,
           -7.8107e-01, -4.2316e-01]],

         [[-1.1169e+00, -1.2613e-01,  1.0105e+00,  ...,  9.6925e-01,
           -5.5107e-01, -1.3483e+00],
          [-1.7315e-01, -5.5711e-01,  1.4907e-01,  ...,  5.4972e-01,
           -5.4654e-01,  3.8671e-01],
          [-2.9083e-01, -5.1327e-02,  7.5448e-02,  ..., -1.7059e+00,
           -1.1477e+00, -1.9621e+00],
          ...,
     

In [7]:
output = m(x)
print(output.shape)
print(output)

torch.Size([20, 33, 101, 201])
tensor([[[[ 3.0888e-03, -3.5187e-02,  1.5840e-02,  ..., -3.0858e-01,
            7.0910e-02,  4.0577e-02],
          [ 4.2363e-02, -2.3334e-01, -2.8223e-01,  ..., -9.0911e-02,
            1.0263e-01, -1.0475e-01],
          [ 1.9115e-01,  8.4852e-02, -4.3576e-02,  ..., -9.1488e-02,
           -2.0682e-01, -2.7228e-01],
          ...,
          [-2.4287e-01, -6.3669e-02, -8.0835e-03,  ...,  1.6564e-03,
           -1.5524e-01,  3.0330e-01],
          [ 6.6839e-02, -8.5765e-02,  2.0772e-01,  ..., -8.9290e-02,
           -3.5153e-02, -2.7544e-02],
          [-1.2360e-01, -3.5910e-02,  1.5467e-01,  ..., -4.3812e-02,
            1.0357e-01, -2.6997e-02]],

         [[-2.2880e-01, -2.1757e-01,  9.6835e-02,  ..., -1.5184e-01,
            6.1549e-02,  8.2961e-02],
          [-7.9088e-02, -1.4668e-01, -2.8206e-01,  ..., -7.0018e-02,
           -9.3926e-02, -1.3119e-01],
          [-1.7663e-01, -1.6976e-01, -1.1429e-01,  ..., -8.8742e-02,
           -2.6300e-01, -8.

2. kernel size = (3,5)

In [8]:
m = nn.ConvTranspose2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
output = m(x)

In [9]:
print(output.shape)
print(output)

torch.Size([20, 33, 93, 100])
tensor([[[[ 5.0389e-04,  5.3426e-01, -2.1117e-01,  ..., -2.6642e-01,
           -4.5219e-01,  2.3866e-01],
          [-3.6205e-02, -2.6664e-01,  8.6134e-02,  ...,  2.0748e-01,
            1.1043e-01, -2.1066e-01],
          [-1.6542e-01, -4.4453e-02, -1.8868e-01,  ..., -1.7840e-01,
           -1.4591e-01, -4.3451e-02],
          ...,
          [ 9.9481e-02,  1.6686e-01,  6.9436e-01,  ..., -1.3680e-01,
           -5.7865e-01,  4.4647e-01],
          [ 1.4071e-01,  5.4496e-02,  3.7167e-03,  ...,  1.0321e-02,
           -5.4499e-01, -1.2777e-01],
          [-1.3107e-02,  3.0066e-01, -1.6464e-01,  ..., -6.0193e-03,
           -5.0272e-01,  8.3964e-02]],

         [[ 2.4201e-01, -6.4132e-01, -1.9758e-01,  ..., -1.5922e-02,
            2.3519e-01,  1.3766e-01],
          [ 3.5214e-01, -1.3203e-01,  2.9446e-01,  ..., -1.7670e-01,
           -1.5023e-02, -2.7902e-01],
          [ 1.7146e-01, -4.7754e-01,  9.1647e-01,  ..., -5.5592e-02,
            1.6526e-01, -4.3

3. downsampling and upsampling

In [10]:
input = torch.randn(1, 16, 12, 12)

In [11]:
downsample = nn.Conv2d(16, 16, 3, stride=2, padding=1)

In [12]:
upsample = nn.ConvTranspose2d(16, 16, 3, stride=2, padding=1)

In [13]:
h = downsample(input)
h.size()

torch.Size([1, 16, 6, 6])

In [14]:
output = upsample(h, output_size=input.size())
output.size()

torch.Size([1, 16, 12, 12])

kernel size 만 맞추면, input size 로 upsampling 될 것.  
단, 당연히 이 conv 는 normal conv 로써,  
cross-channel 연산이 된 것.  

In [21]:
input = torch.randn(1, 16, 12, 12)

In [30]:
downsample = nn.Conv2d(16, 16, 7, stride=2, padding=1)

In [31]:
upsample = nn.ConvTranspose2d(16, 16, 7, stride=2, padding=1)

In [32]:
h = downsample(input)
h.size()

torch.Size([1, 16, 4, 4])

In [33]:
output = upsample(h, output_size=input.size())
output.size()

torch.Size([1, 16, 12, 12])