In [1]:
import torch

#### Convolution layers

##### Conv1d

torch.nn.Conv1d(  
    in_channels, 
    out_channels, 
    kernel_size,  
    stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')

* in_channels (int) – Number of channels in the input image
* out_channels (int) – Number of channels produced by the convolution
* kernel_size (int or tuple) – Size of the convolving kernel  
  
  
* stride (int or tuple, optional) – Stride of the convolution. Default: 1
* padding (int or tuple, optional) – Zero-padding added to both sides of the input. Default: 0  
  
  
* padding_mode (string, optional) – zeros  
  
  
* dilation (int or tuple, optional) – Spacing between kernel elements. Default: 1
* groups (int, optional) – Number of blocked connections from input channels to output channels. Default: 1
* bias (bool, optional) – If True, adds a learnable bias to the output. Default: True

In [3]:
import torch.nn as nn

1. stride = 1, padding = 0

In [11]:
m = nn.Conv1d(16, 33, 3, stride=1)
m

Conv1d(16, 33, kernel_size=(3,), stride=(1,))

In [12]:
input = torch.randn(20, 16, 50)
'''
    20 : batch
    16 : input channel
    50 : feature map
'''
input.shape

torch.Size([20, 16, 50])

In [13]:
output = m(input)
'''
    20 : batch
    33 : output channel
    48 : feature map
'''
output.shape

torch.Size([20, 33, 48])

2. stride = 2, padding = 0

In [14]:
m = nn.Conv1d(16, 33, 3, stride=2)
m

Conv1d(16, 33, kernel_size=(3,), stride=(2,))

In [15]:
input = torch.randn(20, 16, 50)
'''
    20 : batch
    16 : input channel
    50 : feature map
'''
input.shape

torch.Size([20, 16, 50])

In [16]:
output = m(input)
'''
    20 : batch
    33 : output channel
    24 : feature map
'''
output.shape

torch.Size([20, 33, 24])

3. stride = 1, padding = 1

In [10]:
m = nn.Conv1d(16, 33, 3, stride=1, padding=1, bias=False)
m

Conv1d(16, 33, kernel_size=(3,), stride=(1,), padding=(1,), bias=False)

In [11]:
input = torch.randn(20, 16, 50)
'''
    20 : batch
    16 : input channel
    50 : feature map
'''
input.shape

torch.Size([20, 16, 50])

In [12]:
output = m(input)
'''
    20 : batch
    33 : output channel
    50 : feature map
'''
output.shape

torch.Size([20, 33, 50])

4. group = 1

In [63]:
m = nn.Conv1d(2, 4, 5, stride=1, padding=0, groups=1, bias=False)
m

Conv1d(2, 4, kernel_size=(5,), stride=(1,), bias=False)

In [64]:
m.weight.data = torch.ones(4,2,5)
m.weight.data

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [66]:
input_ = torch.ones(1,2,8)
output = m(input_)

In [67]:
output.shape

torch.Size([1, 4, 4])

In [68]:
output

tensor([[[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]]], grad_fn=<SqueezeBackward1>)

5. group = 2

In [69]:
m = nn.Conv1d(2, 4, 5, stride=1, padding=0, groups=2, bias=False)
m

Conv1d(2, 4, kernel_size=(5,), stride=(1,), groups=2, bias=False)

In [70]:
m.weight.data = torch.ones(4,2,5)
m.weight.data

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [71]:
input_ = torch.ones(1,4,8)
output = m(input_)

In [72]:
output.shape

torch.Size([1, 4, 4])

In [73]:
output

tensor([[[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]]], grad_fn=<SqueezeBackward1>)