In [1]:
import torch

#### Convolution layers

##### convTranspose3d

torch.nn.convTranspose3d(  
    in_channels,  
    out_channels,  
    kernel_size,  
    stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros')

* in_channels (int): Number of channels in the input image
* out_channels (int): Number of channels produced by the convolution
* kernel_size (int or tuple): Size of the convolving kernel  
  
  
* stride (int or tuple, optional): Stride of the convolution. Default: 1
* padding (int or tuple, optional): ``dilation * (kernel_size - 1) - padding`` zero-padding will be added to both sides of the input. Default: 0
* output_padding (int or tuple, optional): Additional size added to one side of the output shape. Default: 0  
  
  
* groups (int, optional): Number of blocked connections from input channels to output channels. Default: 1
* bias (bool, optional): If ``True``, adds a learnable bias to the output. Default: ``True``
* dilation (int or tuple, optional): Spacing between kernel elements. Default: 1  


In [2]:
import torch.nn as nn

1. Kernel size = 3 은 (3,3,3)

In [3]:
m = nn.ConvTranspose3d(16, 33, 3, stride=2)

In [6]:
x = torch.randn(3, 16, 5, 5, 10)
x

tensor([[[[[ 9.4618e-01,  1.9766e+00,  1.4897e+00,  ..., -1.1405e+00,
             2.3981e-01,  5.3708e-01],
           [ 7.4507e-01,  1.6777e-01, -8.8295e-01,  ..., -5.9744e-01,
             9.5468e-01, -1.3613e+00],
           [ 8.5741e-01, -1.8419e+00,  1.7351e-02,  ..., -4.0976e-01,
            -3.7875e-01, -1.6969e-01],
           [ 8.4118e-02, -2.2420e+00,  1.4284e+00,  ..., -2.2527e-01,
             2.3519e+00,  1.1800e-01],
           [-1.6604e-01, -1.6195e+00,  9.9773e-01,  ..., -7.9676e-01,
             1.5723e+00,  8.1704e-01]],

          [[ 2.0577e-01,  8.3760e-02, -7.0476e-01,  ..., -1.7815e+00,
            -1.4133e+00, -9.8567e-01],
           [ 3.4528e-01,  1.2715e+00, -3.2823e-01,  ..., -6.3794e-01,
             5.9484e-01, -2.4758e-02],
           [ 8.0514e-01,  9.6329e-02,  1.2877e-01,  ..., -1.6040e+00,
            -8.5186e-01, -1.9690e+00],
           [ 4.8242e-01,  2.6877e-02,  1.6995e+00,  ..., -4.6210e-01,
             7.3762e-01,  1.1690e+00],
           [-2.97

In [7]:
output = m(x)
print(output.shape)
print(output)

torch.Size([3, 33, 11, 11, 21])
tensor([[[[[-8.9945e-02, -1.2621e-01,  1.7589e-02,  ...,  6.0043e-02,
             1.6639e-02, -1.3749e-01],
           [-6.4829e-02, -1.6061e-01, -4.3991e-02,  ...,  7.0369e-02,
             1.0649e-03, -1.1340e-02],
           [-1.6904e-01, -8.9352e-02, -2.0618e-01,  ..., -7.4774e-02,
            -5.6933e-02, -4.1043e-02],
           ...,
           [-4.6939e-02,  6.0027e-02,  3.1802e-01,  ...,  1.8039e-01,
            -1.2739e-01,  1.1008e-01],
           [-5.1926e-02,  3.5068e-02, -1.0801e-01,  ..., -2.3079e-01,
            -1.4064e-02,  3.6846e-02],
           [-2.3604e-02,  8.9169e-02, -3.8557e-02,  ...,  1.0413e-01,
            -8.5942e-02,  1.0128e-02]],

          [[-2.8053e-03, -1.0941e-01,  5.4172e-02,  ..., -3.4196e-02,
             6.2720e-02,  3.3215e-02],
           [ 4.7037e-03, -2.0804e-02,  7.8103e-02,  ..., -1.1644e-01,
            -1.3653e-02, -7.2581e-02],
           [ 1.2854e-01, -2.6069e-02,  2.0014e-02,  ...,  7.9666e-02,
        

2. kernel size = (3, 5, 2)

In [11]:
m = nn.ConvTranspose3d(16, 33, (3, 5, 2), stride=(2, 2, 1), padding=(0, 4, 2))
output = m(x)

In [12]:
print(output.shape)
print(output)

torch.Size([3, 33, 11, 5, 7])
tensor([[[[[ 4.9768e-02,  4.2924e-03,  5.1023e-02,  ...,  1.3446e-01,
             2.1129e-01, -6.2653e-02],
           [-2.2246e-02, -3.6806e-02,  4.2259e-02,  ...,  3.8774e-02,
             8.8504e-03,  2.4484e-03],
           [ 8.0141e-02, -2.3752e-01,  7.2152e-02,  ..., -8.1452e-03,
            -1.1738e-01,  1.6392e-01],
           [-6.0162e-02,  7.1065e-02, -6.7147e-02,  ..., -7.1748e-02,
             1.7337e-01, -3.5215e-01],
           [-2.6223e-01,  8.6672e-02,  2.2480e-01,  ...,  2.3102e-01,
            -8.2279e-02,  1.8135e-02]],

          [[ 1.6377e-01,  2.4294e-01, -1.1693e-01,  ...,  1.2305e-01,
            -1.0262e-01,  2.9331e-01],
           [ 2.7745e-01, -2.0202e-01,  2.4341e-02,  ..., -1.9445e-01,
            -6.1813e-02, -1.0682e-01],
           [-2.5601e-01, -9.3135e-02, -1.5159e-01,  ...,  9.7189e-02,
            -2.7456e-01, -1.2398e-01],
           [ 1.6029e-01,  9.4204e-02,  2.5340e-02,  ..., -1.4359e-02,
            -1.3970e-01,  