In [2]:
import torch

#### Convolution layers

##### convTranspose1d

https://medium.com/@santi.pdp/how-pytorch-transposed-convs1d-work-a7adac63c4a5

torch.nn.convTranspose1d(  
    in_channels,  
    out_channels,  
    kernel_size,  
    stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros')

* in_channels (int): Number of channels in the input image
* out_channels (int): Number of channels produced by the convolution
* kernel_size (int or tuple): Size of the convolving kernel  
  
  
* stride (int or tuple, optional): Stride of the convolution. Default: 1
* padding (int or tuple, optional): ``dilation * (kernel_size - 1) - padding`` zero-padding will be added to both sides of the input. Default: 0
* output_padding (int or tuple, optional): Additional size added to one side of the output shape. Default: 0  
  
  
* groups (int, optional): Number of blocked connections from input channels to output channels. Default: 1
* bias (bool, optional): If ``True``, adds a learnable bias to the output. Default: ``True``
* dilation (int or tuple, optional): Spacing between kernel elements. Default: 1  


In [3]:
import torch.nn as nn

1. First conv1d

In [4]:
x = torch.ones(1,1,7)
x

tensor([[[1., 1., 1., 1., 1., 1., 1.]]])

In [5]:
conv = nn.Conv1d(1,1,3, padding=0, stride=1, bias=False)
conv

Conv1d(1, 1, kernel_size=(3,), stride=(1,), bias=False)

In [6]:
conv.weight.data = torch.ones(1,1,3)
conv.weight.data

tensor([[[1., 1., 1.]]])

In [7]:
y = conv(x)
y

tensor([[[3., 3., 3., 3., 3.]]], grad_fn=<SqueezeBackward1>)

2. transpose convolution

In [8]:
deconv = nn.ConvTranspose1d(1,1,3, padding=0, stride=1, bias=False)
deconv

ConvTranspose1d(1, 1, kernel_size=(3,), stride=(1,), bias=False)

In [9]:
deconv.weight.data = torch.ones(1,1,3) 
deconv.weight.data

tensor([[[1., 1., 1.]]])

In [10]:
x = torch.ones(1,1,1)
x

tensor([[[1.]]])

In [11]:
deconv(x)

tensor([[[1., 1., 1.]]], grad_fn=<SqueezeBackward1>)

In [12]:
x2 = torch.ones(1,1,2)
x2

tensor([[[1., 1.]]])

In [14]:
deconv(x2)

tensor([[[1., 2., 2., 1.]]], grad_fn=<SqueezeBackward1>)

3. transpose convolution with stride > feature width

In [21]:
deconv = nn.ConvTranspose1d(1,1,3, padding=0, stride=4, bias=False)
deconv

ConvTranspose1d(1, 1, kernel_size=(3,), stride=(4,), bias=False)

In [22]:
y = torch.ones(1,1,2)

In [23]:
deconv.weight.data.shape

torch.Size([1, 1, 3])

In [24]:
deconv.weight.data = torch.ones(1,1,3)

In [25]:
deconv(y)

tensor([[[1., 1., 1., 0., 1., 1., 1.]]], grad_fn=<SqueezeBackward1>)

it fills with zeros

4. transpose convolution width stride and padding 

In [58]:
deconv = nn.ConvTranspose1d(1,1,3, padding=1, stride=2, bias=False)
deconv

ConvTranspose1d(1, 1, kernel_size=(3,), stride=(2,), padding=(1,), bias=False)

In [59]:
y = torch.ones(1,1,2)

In [60]:
deconv.weight.data.shape

torch.Size([1, 1, 3])

In [61]:
deconv.weight.data = torch.ones(1,1,3)

In [62]:
deconv(y)

tensor([[[1., 2., 1.]]], grad_fn=<SqueezeBackward1>)