In [1]:
import torch

#### Convolution layers

##### convTranspose2d

torch.nn.convTranspose2d(  
    in_channels,  
    out_channels,  
    kernel_size,  
    stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros')

* in_channels (int): Number of channels in the input image
* out_channels (int): Number of channels produced by the convolution
* kernel_size (int or tuple): Size of the convolving kernel  
  
  
* stride (int or tuple, optional): Stride of the convolution. Default: 1
* padding (int or tuple, optional): ``dilation * (kernel_size - 1) - padding`` zero-padding will be added to both sides of the input. Default: 0
* output_padding (int or tuple, optional): Additional size added to one side of the output shape. Default: 0  
  
  
* groups (int, optional): Number of blocked connections from input channels to output channels. Default: 1
* bias (bool, optional): If ``True``, adds a learnable bias to the output. Default: ``True``
* dilation (int or tuple, optional): Spacing between kernel elements. Default: 1  


In [2]:
import torch.nn as nn

1. Kernel size = 3 은 (3,3), stride = 2

In [3]:
m = nn.ConvTranspose2d(16, 33, 3, stride=2)

In [4]:
x = torch.randn(20, 16, 50, 100)
x

tensor([[[[ 1.7341e-01, -9.3981e-01,  6.8695e-01,  ...,  1.0644e-01,
            5.2216e-01, -1.8029e+00],
          [-1.0688e+00, -5.0667e-01,  1.3747e-01,  ...,  1.4096e+00,
            1.9685e+00,  9.6346e-01],
          [ 9.4250e-01, -6.1982e-01,  1.2161e+00,  ..., -5.4623e-01,
           -3.6717e-01,  6.0106e-01],
          ...,
          [ 5.5886e-01,  3.3689e-02,  6.8842e-01,  ..., -7.3921e-01,
            6.3990e-01,  8.2909e-01],
          [ 3.4329e-01, -8.2350e-01,  2.2917e+00,  ...,  1.2709e+00,
           -4.3162e-01, -4.5169e-01],
          [ 1.1561e-01,  1.4907e+00, -5.0184e-01,  ...,  2.1683e-01,
            1.0824e+00,  6.6514e-03]],

         [[ 1.3319e+00, -1.0611e+00, -1.4241e-01,  ...,  2.3500e-01,
           -2.2306e-01,  9.7445e-02],
          [ 3.2916e-01,  6.6628e-01, -1.5153e+00,  ...,  2.2615e+00,
           -1.0705e-01, -4.2842e-01],
          [-1.6684e+00,  8.7261e-01, -1.6696e+00,  ..., -1.3946e+00,
           -8.3681e-02,  2.1114e-01],
          ...,
     

In [5]:
output = m(x)
print(output.shape)
print(output)

torch.Size([20, 33, 101, 201])
tensor([[[[ 1.2579e-01, -1.7721e-01, -1.9510e-02,  ...,  1.4523e-02,
           -4.2025e-02, -7.4936e-02],
          [-3.6583e-02, -5.6180e-02,  2.2511e-01,  ...,  1.7615e-01,
            1.4092e-01,  1.5065e-02],
          [-1.4451e-01,  3.0987e-02, -6.3718e-02,  ..., -3.2109e-01,
            2.9335e-01, -2.3748e-01],
          ...,
          [ 7.0695e-02,  1.0157e-01, -1.3353e-01,  ..., -3.1870e-02,
            1.5185e-01, -1.7271e-01],
          [ 5.0281e-03,  2.0755e-02,  1.1221e-01,  ..., -1.5655e-03,
            2.9974e-01,  1.6773e-02],
          [ 3.2083e-02,  2.9934e-01,  1.6474e-01,  ...,  4.2312e-01,
           -2.5441e-01,  7.8882e-02]],

         [[ 1.5461e-02, -3.6970e-02,  3.5320e-02,  ...,  1.4686e-01,
           -1.3185e-01, -6.3327e-02],
          [ 6.0041e-02, -1.7180e-01,  1.8515e-01,  ..., -7.4554e-03,
            4.2263e-02, -6.9106e-02],
          [-1.2582e-01, -4.6646e-02,  1.3166e-01,  ..., -1.4549e-01,
            2.8707e-02,  1.

2. kernel size = (3,5)

In [8]:
m = nn.ConvTranspose2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
output = m(x)

In [9]:
print(output.shape)
print(output)

torch.Size([20, 33, 93, 100])
tensor([[[[ 5.0389e-04,  5.3426e-01, -2.1117e-01,  ..., -2.6642e-01,
           -4.5219e-01,  2.3866e-01],
          [-3.6205e-02, -2.6664e-01,  8.6134e-02,  ...,  2.0748e-01,
            1.1043e-01, -2.1066e-01],
          [-1.6542e-01, -4.4453e-02, -1.8868e-01,  ..., -1.7840e-01,
           -1.4591e-01, -4.3451e-02],
          ...,
          [ 9.9481e-02,  1.6686e-01,  6.9436e-01,  ..., -1.3680e-01,
           -5.7865e-01,  4.4647e-01],
          [ 1.4071e-01,  5.4496e-02,  3.7167e-03,  ...,  1.0321e-02,
           -5.4499e-01, -1.2777e-01],
          [-1.3107e-02,  3.0066e-01, -1.6464e-01,  ..., -6.0193e-03,
           -5.0272e-01,  8.3964e-02]],

         [[ 2.4201e-01, -6.4132e-01, -1.9758e-01,  ..., -1.5922e-02,
            2.3519e-01,  1.3766e-01],
          [ 3.5214e-01, -1.3203e-01,  2.9446e-01,  ..., -1.7670e-01,
           -1.5023e-02, -2.7902e-01],
          [ 1.7146e-01, -4.7754e-01,  9.1647e-01,  ..., -5.5592e-02,
            1.6526e-01, -4.3

3. downsampling and upsampling

In [10]:
input = torch.randn(1, 16, 12, 12)

In [11]:
downsample = nn.Conv2d(16, 16, 3, stride=2, padding=1)

In [12]:
upsample = nn.ConvTranspose2d(16, 16, 3, stride=2, padding=1)

In [13]:
h = downsample(input)
h.size()

torch.Size([1, 16, 6, 6])

In [14]:
output = upsample(h, output_size=input.size())
output.size()

torch.Size([1, 16, 12, 12])

kernel size 만 맞추면, input size 로 upsampling 될 것.  
단, 당연히 이 conv 는 normal conv 로써,  
cross-channel 연산이 된 것.  

In [21]:
input = torch.randn(1, 16, 12, 12)

In [30]:
downsample = nn.Conv2d(16, 16, 7, stride=2, padding=1)

In [31]:
upsample = nn.ConvTranspose2d(16, 16, 7, stride=2, padding=1)

In [32]:
h = downsample(input)
h.size()

torch.Size([1, 16, 4, 4])

In [33]:
output = upsample(h, output_size=input.size())
output.size()

torch.Size([1, 16, 12, 12])