In [2]:
import torch

#### Padding layers

##### ConstantPad1d
  
상수값으로 padding 해준다.

torch.nn.ConstantPad1d(  
    padding,  
    value)  
  
* padding (int, tuple) – the size of the padding. If is int, uses the same padding in all boundaries. If a 2-tuple, uses padding_left, padding_right)
* value – constant
  

Input: $(N, C, W_{in})$

Output: $(N, C, W_{out})$

$$W_{out}=W_{in}+padding\_left+padding\_right$$

In [1]:
import torch.nn as nn

1. replicationPad1d

In [3]:
help(nn.ConstantPad1d)

Help on class ConstantPad1d in module torch.nn.modules.padding:

class ConstantPad1d(_ConstantPadNd)
 |  ConstantPad1d(padding, value)
 |  
 |  Pads the input tensor boundaries with a constant value.
 |  
 |  For `N`-dimensional padding, use :func:`torch.nn.functional.pad()`.
 |  
 |  Args:
 |      padding (int, tuple): the size of the padding. If is `int`, uses the same
 |          padding in both boundaries. If a 2-`tuple`, uses
 |          (:math:`\text{padding\_left}`, :math:`\text{padding\_right}`)
 |  
 |  Shape:
 |      - Input: :math:`(N, C, W_{in})`
 |      - Output: :math:`(N, C, W_{out})` where
 |  
 |        :math:`W_{out} = W_{in} + \text{padding\_left} + \text{padding\_right}`
 |  
 |  Examples::
 |  
 |      >>> m = nn.ConstantPad1d(2, 3.5)
 |      >>> input = torch.randn(1, 2, 4)
 |      >>> input
 |      tensor([[[-1.0491, -0.7152, -0.0749,  0.8530],
 |               [-1.3287,  1.8966,  0.1466, -0.2771]]])
 |      >>> m(input)
 |      tensor([[[ 3.5000,  3.5000, -1.049

In [5]:
m = nn.ConstantPad1d(2, 7)

In [6]:
ipt = torch.arange(8, dtype=torch.float).reshape(1, 2, 4)
ipt

tensor([[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]])

In [7]:
output = m(ipt)
output

tensor([[[7., 7., 0., 1., 2., 3., 7., 7.],
         [7., 7., 4., 5., 6., 7., 7., 7.]]])